services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://emUser:emPassword@db:5432/emDB
    volumes:
      - .:/app
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - em_network


  db:
    image: postgres:latest
    container_name: postgresEm
    environment:
      POSTGRES_USER: emUser
      POSTGRES_PASSWORD: emPassword
      POSTGRES_DB: emDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - em_network


  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - em_network

networks:
  em_network:
    driver: bridge

    
volumes:
  postgres_data:
